Create change
GitHub Pull Request: https://github.com/mfcloud/python-zvm-sdk/pull/9

LOG.err changed to LOG.error

Fixed images POST:

    "errmsg": "Unexpected internal error in ZVM SDK, error: (127.0.0.1:57244) SDK server got unexpected exception: AttributeError(\"'Logger' object has no attribute 'err'\",)",

Patch-set: 1
Change-id: If19e39ccc1acb6354cb251e6b4dac2ed9446a4f1
Subject: LOG>err fixed to LOG.error
Branch: refs/heads/master
Status: new
Topic: 
Commit: 8a07543a04afc9c3b8019a460067738fd7abb1b6
Tag: autogenerated:gerrit:newPatchSet
Groups: 8a07543a04afc9c3b8019a460067738fd7abb1b6
Private: false
Work-in-progress: false