print backtrace when got exception
print the call stack when got exception when handling the sdkapi request.

use repr(e) instead of six.text_type to print more detail info when got
syntax error.
eg, for keyerror, the repr(e) would return: "KeyError('response',)"
and six.text_type(e) would return just 'response'.

the backtrace printed in following format
for sdkbaseexception:

[2017-09-28 06:22:58] [ERROR] Traceback (most recent call last):
  File "scripts/sdkserver", line 127, in serve_API
    return_data = api_func(*api_args, **api_kwargs)
  File "/data/root/python-zvm-sdk/zvmsdk/utils.py", line 364, in wrap_func
    return function(*args, **kwargs)
  File "/data/root/python-zvm-sdk/zvmsdk/api.py", line 358, in guest_create_nic
    active=active)
  File "/data/root/python-zvm-sdk/zvmsdk/networkops.py", line 50, in create_nic
    active=active)
  File "/data/root/python-zvm-sdk/zvmsdk/smutclient.py", line 742, in create_nic
    mac_addr=mac_addr, active=active)
  File "/data/root/python-zvm-sdk/zvmsdk/smutclient.py", line 759, in _create_nic
    self._request(requestData)
  File "/data/root/python-zvm-sdk/zvmsdk/smutclient.py", line 105, in _request
    raise exception.SDKSMUTRequestFailed(results, msg)
SDKSMUTRequestFailed: SMUT request failed. RequestData: 'SMAPI nydy0001 API Virtual_Network_Adapter_Create_Extended_DM --operands -k image_device_number=2000 -k adapter_type=QDIO', Results: '{'rs': 4, 'errno': 0, 'strError': 'ULGSMC5404E Image device already defined', 'overallRC': 8, 'rc': 404, 'response': ["(Error) ULTVMU0300E SMAPI API failed: Virtual_Network_Adapter_Create_Extended_DM, overall rc: 8, rc: 404, rs: 4, errno: 0, cmd: /opt/zthin/bin/smcli Virtual_Network_Adapter_Create_Extended_DM --addRCheader -T NYDY0001 -k image_device_number=2000 -k adapter_type=QDIO, out: Adding virtual NIC to NYDY0001's directory entry... ", 'Failed', '  Return Code: 404', '  Reason Code: 4', '  Description: ULGSMC5404E Image device already defined']}'

for syntax exception (internal exception):
Traceback (most recent call last):
  File "scripts/sdkserver", line 126, in serve_API
    return_data = api_func(*api_args, **api_kwargs)
  File "/data/root/python-zvm-sdk/zvmsdk/api.py", line 172, in host_get_info
    return self._hostops.get_info()
  File "/data/root/python-zvm-sdk/zvmsdk/hostops.py", line 42, in get_info
    inv_info = self._smutclient.get_host_info()
  File "/data/root/python-zvm-sdk/zvmsdk/smutclient.py", line 566, in get_host_info
    '\n'.join(results['response']), const.RINV_HOST_KEYWORDS)
KeyError: 'response'

Change-Id: I66e53fce1fb143de7e117cd3868b4dc893326708